---
title: "Lesson Plan"
description: " "
date-modified: "last-modified"
format: html
editor: visual
---

| Lesson | Date | Venue             | Topic                                                                         | Remarks                          |
|--------------|:-------------|--------------|:-----------------|:-------------|
| 1      | 13/1 | SOE/SCIS2 SR B1-2 | [Introduction to Visual Analytics](outline/Lesson01_outline.html)             |                                  |
| 2      | 20/1 | SOE/SCIS2 SR B1-2 | [Designing Graphs to Enlighten](outline/Lesson02_outline.html)                |                                  |
| 3      | 27/1 | SOE/SCIS2 SR B1-2 | [Interactivity in Visual Analytics](outline/Lesson03_outline.html)            |                                  |
| 4      | 3/2  | SOE/SCIS2 SR B1-2 | [Fundamentals of Visual Analytics](outline/Lesson04_outline.html)             |                                  |
| 5      | 17/2 | SOE/SCIS2 SR B1-2 | [Visual Multivariate Analysis](outline/Lesson05_outline.html)                 |                                  |
| 6      | 24/2 | SOE/SCIS2 SR B1-2 | [Visualising and Analysing Time-Oriented Data](outline/Lesson06_outline.html) |                                  |
| 7      | 2/3  | TBC               | [Visualising and Analysing Geographic Data](outline/Lesson07_outline.html)    | Replacing Lunar New Year holiday |
| 8      | 9/3  | SOE/SCIS2 SR B1-2 | [Network Data Visualisation and Analysis](outline/Lesson08_outline.html)      |                                  |
| 9      | 16/3 | SOE/SCIS2 SR B1-2 | [Visualising and Analysing Text Data](outline/Lesson09_outline.html)          |                                  |
| 10     | 23/3 | SOE/SCIS2 SR B1-2 | [Information Dashboard Design](outline/Lesson10_outline.html)                 |                                  |
| 11     | 30/3 | TBC               | Poster Presentation                                                           |                                  |
